[opener]
archive = [{ run = 'unar "$1"', desc = "Extract here" }]
text = [{ run = 'nvim "$@"', block = true }]
image = [{ run = 'open "$@"', block = false }]
video = [{ run = 'inna "$@"', block = false }]

[open]
rules = [
  { mime = "text/*", use = "text" },
  { mime = "image/*", use = "image" },
  { mime = "video/*", use = "video" },

  # { mime = "application/json", use = "text" },
  { name = "*.json", use = "text" },

  # Multiple openers for a single rule
  { name = "*.html", use = ["browser", "text"] },
]
