prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    layout:
      author:
        hidden: true
        # width: <number of columns>
        # grow: <bool> this will make the column grow in size
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Srna IP Update
    filters: is:open repo:serena/tunnel-sg-rules
    limit: 30 # optional limit of rows fetched for this section
issuesSections:
  - title: Created
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Subscribed
    filters: is:open -author:@me
defaults:
  layout:
    prs:
      repo:
        grow: true,
        width: 10
        hidden: false
    # issues: same structure as prs
  prsLimit: 20 # global limit
  issuesLimit: 20 # global limit
  preview:
    open: true # wether to have the preview pane open by default
    width: 60 # width in columns
  refetchIntervalMinutes: 30 # will refetch all sections every 30 minutes
repoPaths: # configure where to locate repos when checking out PRs
  omega-energia/*: ~/projects/work/serena/* # will match dlvhdr/repo-name to ~/code/repos/repo-name
  msouza91/*: ~/projects/personal/* # will match dlvhdr/repo-name to ~/code/repos/repo-name
  msouza91/.dotfiles: ~/.dotfiles # will not match wildcard and map to specified path
keybindings: # optional, define custom keybindings - see more info below
  prs:
    - key: C
      command: >
        tmux split-window -h -c {{.RepoPath}} '
        gh pr checkout {{.PrNumber}} &&
        nvim -c ":Octo pr edit {{.PrNumber}}"
        '

pager:
  diff: bat # or delta for example
